apiVersion: v1
kind: Service
metadata:
  name: nginx-non-headless
  labels:
    app: nginx-non
spec:
  selector:
    app: nginx-non
  ports:
  - port: 80
    targetPort: 81
    name: web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-non
  template:
    metadata:
      labels:
        app: nginx-non
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
          name: web


